{{- if .Values.istio.enabled -}}
{{- $fullName := include "myapp.fullname" . -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $fullName }}
spec:
  hosts:
    - "*.{{ .Values.dnsDomainSuffixPublic }}"
  gateways:
    - istio-system/{{ .Values.istio.gateway }}
  http:
    - match:
        - authority:
            exact: "{{ .Values.istio.host }}.{{ .Values.dnsDomainSuffixPublic }}"
      route:
        - destination:
            port:
              number: 80
            host: {{ $fullName }}.{{ .Release.Namespace }}.svc.cluster.local
  {{- end }}