dependencies:
- name: external-dns
  version: 1.7.8
  repository: https://kubernetes-charts.storage.googleapis.com
  alias: public-dns
- name: external-dns
  version: 1.7.8
  repository: https://kubernetes-charts.storage.googleapis.com
  alias: private-dns
